spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security
    username: postgres
    password: 111
  jpa:
    hibernate:
     ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never
